/**
 * Credential Request Types
 * Based on Fap.Domain.DTOs.Credential.CredentialRequests
 */

export interface RequestCredentialRequest {
  certificateType: "SubjectCompletion" | "SemesterCompletion" | "RoadmapCompletion";
  subjectId?: string;
  semesterId?: string;
  roadmapId?: string;
  notes?: string;
}

export interface CredentialRequestDto {
  id: string;
  studentName: string;
  studentCode: string;
  certificateType: string;
  subjectName?: string;
  semesterName?: string;
  roadmapName?: string;
  completionDate?: string;
  finalGrade?: number;
  letterGrade?: string;
  status: string;
  isAutoGenerated: boolean;
  createdAt: string;
  studentNotes?: string;
  adminNotes?: string;
}

export interface GraduationEligibilityDto {
  studentId: string;
  studentCode: string;
  studentName: string;
  isEligible: boolean;
  totalSubjects: number;
  completedSubjects: number;
  failedSubjects: number;
  inProgressSubjects: number;
  openSubjects: number;
  lockedSubjects: number;
  requiredCredits: number;
  completedCredits: number;
  outstandingSubjects: Array<{
    subjectId: string;
    subjectCode: string;
    subjectName: string;
    credits: number;
    status: string;
  }>;
  message?: string;
  graduationDate?: string;
}

